version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-multidb
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - backend

  usuario-server:
    build: ./usuario-server
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-multidb:3306/usuarios_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - mysql
      - eureka-server
    networks:
      - backend

  proyectofacultad-service:
    build: ./proyectofacultad-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-multidb:3306/proyectofacultad
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      USUARIO_SERVER_URL: http://usuario-server:8082
    depends_on:
      - mysql
      - eureka-server
    networks:
      - backend

  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
    networks:
      - backend
  api-gateway:
      build: ./api-gateway
      ports:
        - "8090:8090"
      environment:
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      depends_on:
        - eureka-server
      networks:
        - backend

volumes:
  mysql-data:

networks:
  backend:
    driver: bridge