server.port=8090

spring.application.name=api-gateway
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true
spring.cloud.gateway.routes[0].id=usuario-server
spring.cloud.gateway.routes[0].uri=lb://usuario-server
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/usuarios/**
spring.cloud.gateway.routes[1].id=proyectofacultad-service
spring.cloud.gateway.routes[1].uri=lb://proyectofacultad-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/materias/**

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka/}
eureka.instance.instance-id=${spring.application.name}:${random.value}
eureka.instance.prefer-ip-address=true