server.port=8090

spring.application.name=api-gateway
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true
spring.cloud.gateway.routes[0].id=usuario-server
spring.cloud.gateway.routes[0].uri=lb://usuario-server
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/usuarios/**
spring.cloud.gateway.routes[1].id=proyectofacultad-service
spring.cloud.gateway.routes[1].uri=lb://proyectofacultad-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/materias/**
spring.cloud.gateway.routes[2].id=usuario-auth
spring.cloud.gateway.routes[2].uri=lb://usuario-server
spring.cloud.gateway.routes[2].predicates[0]=Path=/auth/**

spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins=http://localhost:5173
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods=GET,POST,PUT,DELETE
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allow-credentials=true

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka/}
eureka.instance.instance-id=${spring.application.name}:${random.value}
eureka.instance.prefer-ip-address=true

#Las siguientes configuraciones se requieren para evitar errores cuando se está levantando el sistema,
#para que el Eureka Server conozca bien al API Gateway.
#Con esto hacemos Timeouts un poco más largos.
spring.cloud.gateway.httpclient.connect-timeout=1000
spring.cloud.gateway.httpclient.response-timeout=5s

#Con esto se trata de reconectar.
spring.cloud.gateway.loadbalancer.retry.enabled=true
spring.cloud.loadbalancer.retry.max-retries-on-next-service-instance=2
spring.cloud.loadbalancer.retry.max-retries-on-same-service-instance=1