server:
  port: 8090

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  
          lower-case-service-id: true
      routes:
        - id: usuario-server
          uri: lb://usuario-server
          predicates:
            - Path=/api/usuarios/**
        - id: proyectofacultad-service
          uri: lb://proyectofacultad-service
          predicates:
            - Path=/api/materias/**

eureka:
  client:
    register-with-eureka=true
    fetch-registry=true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true
