spring.application.name=usuario-server

# Configuración del puerto
server.port=8082

# Configuración de la base de datos
#spring.datasource.url=jdbc:mysql://127.0.0.1:3306/usuarios_db
spring.datasource.url=jdbc:mysql://mysql-multidb:3306/usuarios_db
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.hbm2ddl.import_files=import_active_users.sql,import_inactive_users.sql
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Configuraciones para Eureka.
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.instance-id=${spring.application.name}:${random.value}
eureka.instance.prefer-ip-address: true

# Clave secreta para firmar JWTs (¡cambia esto en producción!)
jwt.secret=claveParaJwtUtil
jwt.expirationMs=86400000 # 24 horas
